<div id="mid" class="mid">
<h3>Zde bude hlavní text.</h3>


<object data="http://zsukaplicky.cz/novaverze/body/Endoskopie.pdf" type="application/pdf" width="100%" height="100%">
  alt : <a href="data/test.pdf">test.pdf</a>
</object>
<!--
<embed src="https://drive.google.com/viewerng/
viewer?embedded=true&url=http://zsukaplicky.cz/novaverze/body/Endoskopie.pdf" width="auto" height="auto" type="application/pdf">      -->

<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Mauris metus. Fusce dui leo, imperdiet in, aliquam sit amet, feugiat eu, orci. Ut tempus purus at lorem. Curabitur bibendum justo non orci. Ut tempus purus at lorem. Duis condimentum augue id magna semper rutrum. Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Duis pulvinar. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Fusce tellus. Suspendisse nisl. Phasellus rhoncus. Suspendisse sagittis ultrices augue.  </p>

<p>In convallis. Fusce aliquam vestibulum ipsum. Maecenas ipsum velit, consectetuer eu lobortis ut, dictum at dui. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Fusce consectetuer risus a nunc. Nullam justo enim, consectetuer nec, ullamcorper ac, vestibulum in, elit. Mauris metus. Morbi scelerisque luctus velit. Nullam lectus justo, vulputate eget mollis sed, tempor sed magna. Etiam ligula pede, sagittis quis, interdum ultricies, scelerisque eu. Duis condimentum augue id magna semper rutrum. Vivamus ac leo pretium faucibus.                      </p>

<p>Sed elit dui, pellentesque a, faucibus vel, interdum nec, diam. Nullam rhoncus aliquam metus. Nunc dapibus tortor vel mi dapibus sollicitudin. Vivamus ac leo pretium faucibus. Praesent dapibus. Aliquam erat volutpat. Morbi scelerisque luctus velit. Ut tempus purus at lorem. In rutrum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat. Vivamus porttitor turpis ac leo. Nullam faucibus mi quis velit. Fusce nibh. Mauris tincidunt sem sed arcu. Quisque tincidunt scelerisque libero. Fusce consectetuer risus a nunc. Nulla accumsan, elit sit amet varius semper, nulla mauris mollis quam, tempor suscipit diam nulla vel leo. Praesent dapibus. Praesent vitae arcu tempor neque lacinia pretium.   </p>

<p>Fusce tellus. Mauris metus. Etiam egestas wisi a erat. Nullam at arcu a est sollicitudin euismod. Maecenas libero. Donec ipsum massa, ullamcorper in, auctor et, scelerisque sed, est. Nullam at arcu a est sollicitudin euismod. Nulla non lectus sed nisl molestie malesuada. Aenean id metus id velit ullamcorper pulvinar. Suspendisse sagittis ultrices augue. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Donec quis nibh at felis congue commodo. Curabitur ligula sapien, pulvinar a vestibulum quis, facilisis vel sapien. Integer rutrum, orci vestibulum ullamcorper ultricies, lacus quam ultricies odio, vitae placerat pede sem sit amet enim. Proin pede metus, vulputate nec, fermentum fringilla, vehicula vitae, justo. Mauris tincidunt sem sed arcu. In sem justo, commodo ut, suscipit at, pharetra vitae, orci. Nullam at arcu a est sollicitudin euismod.                                                      </p>

<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Etiam quis quam. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Etiam egestas wisi a erat. Curabitur sagittis hendrerit ante. Etiam egestas wisi a erat. Nam quis nulla. Duis risus. Maecenas sollicitudin. Maecenas libero. Duis condimentum augue id magna semper rutrum. Maecenas sollicitudin. Maecenas aliquet accumsan leo. Curabitur bibendum justo non orci. Nulla est. Mauris metus. Vestibulum fermentum tortor id mi. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.                                                                                      </p>
</div>